define(['connectionManager'], function (connectionManager) {
'use strict';
function Controller(page) {
var api=connectionManager.currentApiClient(),state={shows:[],data:null,columnCount:1,cells:{},selectedColumn:0,refreshToken:Date.now(),syncing:false,scrollSource:null,scrollRatio:0,scrollFrame:0,syncTimer:0};
function setPageActive(active){document.documentElement.classList.toggle('ctsi-page-active',active);}
setPageActive(true);
page.addEventListener('viewshow',function(){setPageActive(true);});
page.addEventListener('viewhide',function(){setPageActive(false);});
function url(path,args){return api.getUrl('ProviderImageHelper/'+path,args||{});}function request(path,args){return api.getJSON(url(path,args));}function post(path,body){return api.ajax({type:'POST',url:url(path),data:JSON.stringify(body),contentType:'application/json'});}function del(path){return api.ajax({type:'DELETE',url:url(path)});}function setLoading(active,message){page.classList.toggle('ctsi-loading',active);page.querySelector('#ctsiLoad').disabled=active;page.querySelector('#ctsiStatus').textContent=message||'';}function esc(s){return String(s||'').replace(/[&<>"']/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c];});}function toast(s){var e=document.createElement('div');e.className='ctsi-toast';e.textContent=s;document.body.appendChild(e);setTimeout(function(){e.remove();},3000);}function key(seasonId,type){return seasonId+'|'+type;}function cellKey(k,col){return k+'|'+col;}
function sourceLabel(provider){var p=String(provider||'Unknown').toLowerCase();if(p.indexOf('moviedb')>=0||p.indexOf('movie database')>=0||p==='tmdb')return'TheMovieDb · Season';if(p.indexOf('tvdb')>=0&&p.indexOf('series')>=0)return'TheTVDB · Series';if(p.indexOf('tvdb')>=0)return'TheTVDB · Season';if(p.indexOf('fanart')>=0)return'FanArt';return provider||'Unknown';}function secure(v){return String(v||'').replace(/^http:/i,'https:');}
function discover(){return request('Discover',{Filter:page.querySelector('#ctsiFilter').value,Search:page.querySelector('#ctsiSearch').value}).then(function(x){state.shows=x;page.querySelector('#ctsiShows').innerHTML=x.map(function(s){return'<option value="'+esc(s.Name)+'"></option>';}).join('');});}
function currentCandidate(season,type){var exists=type==='Poster'?season.CurrentPoster:season.CurrentBanner,itemId=type==='Poster'?season.CurrentPosterItemId:season.CurrentBannerItemId,imageTag=type==='Poster'?season.CurrentPosterTag:season.CurrentBannerTag;return exists?{Current:true,SeasonId:season.Id,ImageItemId:itemId,ImageTag:imageTag,Type:type,Provider:'Current'}:null;}
function candidateImage(candidate){if(candidate.Current){var imageUrl=api.getImageUrl(candidate.ImageItemId,{type:candidate.Type==='Poster'?'Primary':'Banner',tag:candidate.ImageTag,quality:90});return imageUrl+(imageUrl.indexOf('?')>=0?'&':'?')+'ctsi='+state.refreshToken;}return secure(candidate.ThumbnailUrl||candidate.Url);}
function candidateCard(candidate,context,k,col){var src=candidateImage(candidate),meta=sourceLabel(candidate.Provider)+' · '+(candidate.Width||'?')+'×'+(candidate.Height||'?'),apply=candidate.Current?'':'<button class="ctsi-icon ctsi-now" title="Apply this image now">Apply</button>',controls='';if(context==='compare')controls='<button class="ctsi-icon ctsi-tick" title="Select this comparison column">✓</button>'+(state.columnCount>1?'<button class="ctsi-icon ctsi-remove" title="Remove this comparison column">×</button>':'');return'<div class="ctsi-card '+candidate.Type.toLowerCase()+(candidate.Current?' current':'')+'" draggable="true" data-origin="'+context+'" data-key="'+k+'" data-col="'+col+'" data-url="'+esc(candidate.Url||'')+'"><img loading="lazy" referrerpolicy="no-referrer" src="'+esc(src)+'" data-fallback="'+esc(candidate.Current?'':secure(candidate.Url))+'">'+(candidate.Current?'':'<div class="ctsi-meta">'+apply+'<span class="ctsi-meta-text">'+esc(meta)+'</span></div>')+controls+'</div>';}
function slot(label,content,classes,attrs){return'<div class="ctsi-slot-wrap '+(classes||'')+'"><span class="ctsi-slot-label">'+label+'</span><div class="ctsi-slot" '+(attrs||'')+'>'+content+'</div></div>';}
function lane(season,type,images){var k=key(season.Id,type),current=currentCandidate(season,type),html=slot('Current',current?candidateCard(current,'current',k,-1):'<span>None</span>','ctsi-current','data-key="'+k+'" data-col="-1" data-type="'+type+'"');for(var col=0;col<state.columnCount;col++){var candidate=state.cells[cellKey(k,col)];html+=slot('&nbsp;',candidate?candidateCard(candidate,'compare',k,col):'<span>Drop candidate</span>','ctsi-compare '+(state.selectedColumn===col?'ctsi-column-selected':''),'data-key="'+k+'" data-col="'+col+'" data-type="'+type+'"');}html+=slot('&nbsp;','<span class="ctsi-plus-circle">＋</span>','ctsi-new','data-key="'+k+'" data-col="'+state.columnCount+'" data-type="'+type+'"');return'<div class="ctsi-lane '+type.toLowerCase()+'"><strong>'+type+'</strong><div class="ctsi-workspace">'+html+'</div><div class="ctsi-pool" title="Shift+mouse-wheel also scrolls horizontally"><div class="ctsi-strip '+type.toLowerCase()+'">'+images.map(function(i){return candidateCard(i,'pool',k,-2);}).join('')+'</div></div></div>';}
function compareHeader(position){var columns='';for(var i=0;i<state.columnCount;i++)columns+='<div class="ctsi-header-column '+(state.selectedColumn===i?'selected':'')+'"><button class="ctsi-header-select" data-col="'+i+'" title="Select this comparison column">'+(state.selectedColumn===i?'✓':'Select')+'</button>'+(state.selectedColumn===i?'<button is="emby-button" class="raised button-submit ctsi-apply-all">Apply All</button>':'')+(state.columnCount>1?'<button class="ctsi-header-remove" data-col="'+i+'" title="Remove this comparison column">×</button>':'')+'</div>';return'<div class="ctsi-compare-heading '+position+'"><div class="ctsi-heading-label" style="width:'+(state.columnCount*138)+'px">Compare Columns</div><div class="ctsi-heading-row"><div class="ctsi-heading-current"></div>'+columns+'<div class="ctsi-heading-add"></div></div></div>';}
function render(){var layout=page.querySelector('#ctsiLayout').value;if(!state.data){page.querySelector('#ctsiWork').innerHTML='';return;}page.querySelector('#ctsiWork').innerHTML='<div class="ctsi-main-head"><h2>'+esc(state.data.Name)+'</h2></div>'+compareHeader('top')+state.data.Seasons.map(function(s){return'<section class="ctsi-season"><h3>'+esc(s.Name)+'</h3>'+(layout!=='banner'?lane(s,'Poster',s.Posters):'')+(layout!=='poster'?lane(s,'Banner',s.Banners):'')+'</section>';}).join('')+compareHeader('bottom');bind();}
function findPoolCandidate(k,urlValue){var bits=k.split('|'),season=state.data.Seasons.find(function(s){return s.Id===bits[0];}),items=bits[1]==='Poster'?season.Posters:season.Banners;return items.find(function(i){return i.Url===urlValue;});}
function dragPayload(card){var k=card.dataset.key,col=Number(card.dataset.col),candidate;if(card.dataset.origin==='current'){var bits=k.split('|'),season=state.data.Seasons.find(function(s){return s.Id===bits[0];});candidate=currentCandidate(season,bits[1]);}else if(card.dataset.origin==='compare')candidate=state.cells[cellKey(k,col)];else candidate=findPoolCandidate(k,card.dataset.url||card.getAttribute('data-url'));return{candidate:candidate,sourceKey:k};}
function insertColumn(index){var moved={};Object.keys(state.cells).forEach(function(old){var bits=old.split('|'),col=Number(bits.pop()),base=bits.join('|');moved[cellKey(base,col>=index?col+1:col)]=state.cells[old];});state.cells=moved;state.columnCount++;if(state.selectedColumn>=index)state.selectedColumn++;}
function removeColumn(index){if(state.columnCount<=1){toast('At least one comparison column is required.');return;}var moved={};Object.keys(state.cells).forEach(function(old){var bits=old.split('|'),col=Number(bits.pop()),base=bits.join('|');if(col!==index)moved[cellKey(base,col>index?col-1:col)]=state.cells[old];});state.cells=moved;state.columnCount--;if(state.selectedColumn===index)state.selectedColumn=0;else if(state.selectedColumn>index)state.selectedColumn--;render();}
function drop(cell,e){e.preventDefault();var payload=JSON.parse(e.dataTransfer.getData('application/json')),candidate=payload.candidate,k=cell.dataset.key,type=cell.dataset.type;if(!candidate||candidate.Type!==type){toast('Only '+type+' candidates can be dropped here.');return;}if(candidate.Current&&candidate.SeasonId!==k.split('|')[0]){toast('A current image can only be compared within its own season.');return;}var col=Number(cell.dataset.col);if(cell.closest('.ctsi-new')){state.cells[cellKey(k,state.columnCount)]=candidate;state.columnCount++;}else{var box=cell.getBoundingClientRect(),ratio=(e.clientX-box.left)/box.width;if(ratio<.16||ratio>.84){var insert=ratio<.5?col:col+1;insertColumn(insert);state.cells[cellKey(k,insert)]=candidate;}else state.cells[cellKey(k,col)]=candidate;}render();}
function applyCandidate(k,candidate){if(!candidate){toast('That comparison cell is empty.');return Promise.resolve(false);}var bits=k.split('|');if(candidate.Current&&candidate.ImageItemId===bits[0]){toast('Current image is already applied.');return Promise.resolve(false);}return post('Apply',{SeasonId:bits[0],ImageType:bits[1],ImageUrl:candidate.Current?null:candidate.Url,SourceItemId:candidate.Current?candidate.ImageItemId:null}).then(function(){return true;});}
function fetchArgs(seriesId){return{SeriesId:seriesId,IncludeAllLanguages:page.querySelector('#ctsiAllLanguages').checked};}function refreshData(){if(!state.data)return Promise.resolve();return request('Fetch',fetchArgs(state.data.SeriesId)).then(function(x){state.data=x;state.refreshToken=Date.now();render();});}
function applyAll(){var jobs=[];state.data.Seasons.forEach(function(s){['Poster','Banner'].forEach(function(type){var k=key(s.Id,type),candidate=state.cells[cellKey(k,state.selectedColumn)];if(candidate&&!candidate.Current)jobs.push(function(){return applyCandidate(k,candidate);});});});var chain=Promise.resolve(),done=0;jobs.forEach(function(job){chain=chain.then(job).then(function(applied){if(applied)done++;});});chain.then(function(){return refreshData();}).then(function(){toast(done+' image(s) applied from the selected comparison column.');}).catch(function(e){toast('Apply failed: '+(e.message||e));});}
function synchronizePool(p){if(state.syncing&&state.scrollSource!==p)return;state.syncing=true;state.scrollSource=p;var max=p.scrollWidth-p.clientWidth;state.scrollRatio=max?p.scrollLeft/max:0;if(!state.scrollFrame)state.scrollFrame=requestAnimationFrame(function(){state.scrollFrame=0;page.querySelectorAll('.ctsi-pool').forEach(function(q){if(q!==state.scrollSource){var target=state.scrollRatio*(q.scrollWidth-q.clientWidth);if(Math.abs(q.scrollLeft-target)>.5)q.scrollLeft=target;}});clearTimeout(state.syncTimer);state.syncTimer=setTimeout(function(){state.syncing=false;state.scrollSource=null;},45);});}
function bind(){page.querySelectorAll('.ctsi-card').forEach(function(card){card.ondragstart=function(e){e.dataTransfer.setData('application/json',JSON.stringify(dragPayload(card)));};var img=card.querySelector('img');img.onerror=function(){var fallback=img.dataset.fallback;if(fallback&&img.src!==fallback){img.dataset.fallback='';img.src=fallback;}else card.classList.add('image-error');};var tick=card.querySelector('.ctsi-tick');if(tick)tick.onclick=function(e){e.stopPropagation();state.selectedColumn=Number(card.dataset.col);render();};var now=card.querySelector('.ctsi-now');now.onclick=function(e){e.stopPropagation();applyCandidate(card.dataset.key,dragPayload(card).candidate).then(function(ok){if(ok)return refreshData();}).then(function(){toast('Image applied.');});};var remove=card.querySelector('.ctsi-remove');if(remove)remove.onclick=function(e){e.stopPropagation();removeColumn(Number(card.dataset.col));};});page.querySelectorAll('.ctsi-compare .ctsi-slot,.ctsi-new .ctsi-slot').forEach(function(cell){cell.ondragover=function(e){e.preventDefault();if(cell.closest('.ctsi-compare')){var b=cell.getBoundingClientRect(),r=(e.clientX-b.left)/b.width;cell.classList.toggle('edge-left',r<.16);cell.classList.toggle('edge-right',r>.84);}};cell.ondragleave=function(){cell.classList.remove('edge-left','edge-right');};cell.ondrop=function(e){drop(cell,e);};});page.querySelectorAll('.ctsi-header-select').forEach(function(b){b.onclick=function(){state.selectedColumn=Number(b.dataset.col);render();};});page.querySelectorAll('.ctsi-header-remove').forEach(function(b){b.onclick=function(){removeColumn(Number(b.dataset.col));};});page.querySelectorAll('.ctsi-apply-all').forEach(function(b){b.onclick=applyAll;});page.querySelectorAll('.ctsi-pool').forEach(function(p){p.onwheel=function(e){if(e.shiftKey){e.preventDefault();p.scrollLeft+=e.deltaY;}};p.onscroll=function(){synchronizePool(p);};});}
page.querySelector('#ctsiFilter').addEventListener('change',discover);page.querySelector('#ctsiSearch').addEventListener('input',discover);page.querySelector('#ctsiLayout').addEventListener('change',render);page.querySelector('#ctsiLabels').addEventListener('click',function(){var hidden=page.classList.toggle('ctsi-hide-labels');this.textContent=hidden?'Show image labels':'Hide image labels';});page.querySelector('#ctsiAllLanguages').addEventListener('change',function(){if(state.data){setLoading(true,this.checked?'Showing cached images in all languages…':'Filtering cached images to the current language…');refreshData().then(function(){setLoading(false,'Language filter updated from the provider cache.');}).catch(function(e){setLoading(false,'Language refresh failed.');toast('Language refresh failed: '+(e.message||e));});}});page.querySelector('#ctsiClearCache').addEventListener('click',function(){this.disabled=true;var button=this;del('Cache').then(function(x){toast('Provider cache cleared ('+(x.FilesRemoved||0)+' files). The next load will fetch fresh images.');}).catch(function(e){toast('Could not clear cache: '+(e.message||e));}).then(function(){button.disabled=false;});});page.querySelector('#ctsiLoad').addEventListener('click',function(){var name=page.querySelector('#ctsiSearch').value,s=state.shows.find(function(x){return x.Name===name;})||state.shows[0];if(!s)return;var isSame=state.data&&state.data.SeriesId===s.Id,started=Date.now(),all=page.querySelector('#ctsiAllLanguages').checked;setLoading(true,'Fetching '+s.Name+(all?' in all languages…':' in the library’s preferred image language…'));request('Fetch',fetchArgs(s.Id)).then(function(x){state.data=x;state.refreshToken=Date.now();if(!isSame){state.columnCount=1;state.cells={};state.selectedColumn=0;}render();setLoading(false,'Loaded '+x.Seasons.length+' seasons in '+((Date.now()-started)/1000).toFixed(1)+'s. Off-screen images load as you scroll.');}).catch(function(e){setLoading(false,'Fetch failed.');toast('Fetch failed: '+(e.message||e));});});discover();
}
return Controller;
});
